# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messagebox.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_messagebox(object):
    def setupUi(self, messagebox):
        messagebox.setObjectName("messagebox")
        messagebox.resize(750, 400)
        self.msgmenu = QtWidgets.QWidget(messagebox)
        self.msgmenu.setStyleSheet("#msgmenu {background:url(:/background_img/images/images/options.png);\n"
"background-repeat: no-repeat;\n"
"background-origin: cover;\n"
"background-clip: padding;\n"
"background-position: center;\n"
"border-radius:0px;border: 0px solid #666;\n"
"}\n"
"\n"
"#btn_scanqr , #btn_printer , #btn_donate {border: 0px solid #666;}\n"
"#lbl_donate ,#lbl_printer ,#lbl_scanqr {color:rgb(62, 62, 62); font:20 14pt \"Piboto Condensed\";\n"
"}\n"
"\n"
"\n"
"#optionstitle{color:rgb(62, 62, 62); font:20 17pt \"Piboto Condensed\";}")
        self.msgmenu.setObjectName("msgmenu")
        self.btn_scanqr = QtWidgets.QPushButton(self.msgmenu)
        self.btn_scanqr.setGeometry(QtCore.QRect(40, 108, 172, 272))
        self.btn_scanqr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_scanqr.setText("")
        self.btn_scanqr.setObjectName("btn_scanqr")
        self.btn_printer = QtWidgets.QPushButton(self.msgmenu)
        self.btn_printer.setGeometry(QtCore.QRect(290, 108, 172, 272))
        self.btn_printer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_printer.setText("")
        self.btn_printer.setObjectName("btn_printer")
        self.btn_donate = QtWidgets.QPushButton(self.msgmenu)
        self.btn_donate.setGeometry(QtCore.QRect(529, 108, 172, 272))
        self.btn_donate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_donate.setText("")
        self.btn_donate.setObjectName("btn_donate")
        self.optionstitle = QtWidgets.QLabel(self.msgmenu)
        self.optionstitle.setGeometry(QtCore.QRect(20, 30, 701, 31))
        self.optionstitle.setAlignment(QtCore.Qt.AlignCenter)
        self.optionstitle.setObjectName("optionstitle")
        self.lbl_scanqr = QtWidgets.QLabel(self.msgmenu)
        self.lbl_scanqr.setGeometry(QtCore.QRect(40, 330, 172, 41))
        self.lbl_scanqr.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_scanqr.setObjectName("lbl_scanqr")
        self.lbl_printer = QtWidgets.QLabel(self.msgmenu)
        self.lbl_printer.setGeometry(QtCore.QRect(290, 330, 172, 41))
        self.lbl_printer.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_printer.setObjectName("lbl_printer")
        self.lbl_donate = QtWidgets.QLabel(self.msgmenu)
        self.lbl_donate.setGeometry(QtCore.QRect(529, 330, 172, 41))
        self.lbl_donate.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_donate.setObjectName("lbl_donate")
        self.optionstitle.raise_()
        self.lbl_scanqr.raise_()
        self.lbl_printer.raise_()
        self.lbl_donate.raise_()
        self.btn_scanqr.raise_()
        self.btn_printer.raise_()
        self.btn_donate.raise_()
        messagebox.setCentralWidget(self.msgmenu)

        self.retranslateUi(messagebox)
        QtCore.QMetaObject.connectSlotsByName(messagebox)

    def retranslateUi(self, messagebox):
        _translate = QtCore.QCoreApplication.translate
        messagebox.setWindowTitle(_translate("messagebox", "MainWindow"))
        self.optionstitle.setText(_translate("messagebox", "Veuillez choisir la méthode pour récupérer vos points "))
        self.lbl_scanqr.setText(_translate("messagebox", "Scanner le Qr code"))
        self.lbl_printer.setText(_translate("messagebox", "Imprimer le ticket"))
        self.lbl_donate.setText(_translate("messagebox", "Offrir un don"))

from .resources import *
