# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pano.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "#centralwidget {background-image:url(:/background_img/images/images/bg.png);\n"
            "background-color:black;\n"
            " background-origin: cover;\n"
            "background-clip: padding;\n"
            "background-position: center;\n"
            "background-repeat: no-repeat;}\n"
            "\n"
            "#text_p , #text_c {color:white}\n"
            "#number_c, #number_p , #total_number ,#text_total_numb ,#time {color:#737373;}\n"
            "\n"
            "#butt_finish , #butt_help{\n"
            "color:#737373;\n"
            "}\n"
            "\n"
            "#butt_finish, #total_number{border-radius: 55px;border: 4px solid #666;}\n"
            "#butt_help {border-radius: 20px;border: 3px solid #666;font: 25 20pt \"Bahnschrift Light SemiCondensed\"}\n"
            "\n"
            "#butt_finish:hover , #butt_help:hover {\n"
            "background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.306818 rgba(0, 0, 0, 5), stop:0.653409 rgba(0, 0, 0, 14), stop:0.926136 rgba(0, 0, 0, 30))\n"
            "}\n"
            "\n"
            "#total_number , #number_c , #number_p{font: 25 50pt \"Bahnschrift Light SemiCondensed\";}\n"
            "#butt_finish{font: 25 25pt \"Bahnschrift Light SemiCondensed\";}\n"
            "\n"
            "#text_p , #text_c {font: 25 20pt \"Bahnschrift SemiCondensed\";}\n"
            "#text_total_numb{font: 25 20pt \"Bahnschrift SemiCondensed\";}\n"
            "\n"
            "#level_c , #level_p{\n"
            "    backgroundcolor:rgba(0,0,0,0);\n"
            "    border: 1px solid grey;\n"
            "    border-radius: 3px;}\n"
            "#level_p::chunk , #level_c::chunk{\n"
            "background-color: #6a993d;\n"
            "width: 8px;\n"
            "margin: 1px;}\n"
            "#time{font: 25 20pt \"Bahnschrift SemiCondensed\";}\n"
            "")
        self.centralwidget.setObjectName("centralwidget")
        self.butt_help = QtWidgets.QPushButton(self.centralwidget)
        self.butt_help.setGeometry(QtCore.QRect(27, 535, 40, 40))
        self.butt_help.setObjectName("butt_help")
        self.number_p = QtWidgets.QLabel(self.centralwidget)
        self.number_p.setGeometry(QtCore.QRect(665, 400, 180, 70))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.number_p.setFont(font)
        self.number_p.setAlignment(QtCore.Qt.AlignCenter)
        self.number_p.setObjectName("number_p")
        self.number_c = QtWidgets.QLabel(self.centralwidget)
        self.number_c.setGeometry(QtCore.QRect(180, 400, 180, 70))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.number_c.setFont(font)
        self.number_c.setAlignment(QtCore.Qt.AlignCenter)
        self.number_c.setObjectName("number_c")
        self.total_number = QtWidgets.QLabel(self.centralwidget)
        self.total_number.setGeometry(QtCore.QRect(460, 132, 110, 110))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.total_number.setFont(font)
        self.total_number.setAlignment(QtCore.Qt.AlignCenter)
        self.total_number.setObjectName("total_number")
        self.level_p = QtWidgets.QProgressBar(self.centralwidget)
        self.level_p.setGeometry(QtCore.QRect(817, 86, 34, 17))
        self.level_p.setProperty("value", 100)
        self.level_p.setTextVisible(False)
        self.level_p.setObjectName("level_p")
        self.butt_finish = QtWidgets.QPushButton(self.centralwidget)
        self.butt_finish.setGeometry(QtCore.QRect(460, 400, 110, 110))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.butt_finish.setFont(font)
        self.butt_finish.setObjectName("butt_finish")
        self.text_total_numb = QtWidgets.QLabel(self.centralwidget)
        self.text_total_numb.setGeometry(QtCore.QRect(430, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.text_total_numb.setFont(font)
        self.text_total_numb.setAlignment(QtCore.Qt.AlignCenter)
        self.text_total_numb.setObjectName("text_total_numb")
        self.text_p = QtWidgets.QLabel(self.centralwidget)
        self.text_p.setGeometry(QtCore.QRect(655, 120, 200, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.text_p.setFont(font)
        self.text_p.setObjectName("text_p")
        self.text_c = QtWidgets.QLabel(self.centralwidget)
        self.text_c.setGeometry(QtCore.QRect(168, 120, 200, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.text_c.setFont(font)
        self.text_c.setObjectName("text_c")
        self.level_c = QtWidgets.QProgressBar(self.centralwidget)
        self.level_c.setGeometry(QtCore.QRect(332, 86, 34, 17))
        self.level_c.setProperty("value", 100)
        self.level_c.setTextVisible(False)
        self.level_c.setObjectName("level_c")
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(0, 5, 1024, 29))
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.butt_help.raise_()
        self.number_p.raise_()
        self.number_c.raise_()
        self.total_number.raise_()
        self.level_p.raise_()
        self.text_total_numb.raise_()
        self.text_c.raise_()
        self.level_c.raise_()
        self.butt_finish.raise_()
        self.text_p.raise_()
        self.time.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.butt_help.setText(_translate("MainWindow", "?"))
        self.number_p.setText(_translate("MainWindow", "07"))
        self.number_c.setText(_translate("MainWindow", "15"))
        self.total_number.setText(_translate("MainWindow", "22"))
        self.butt_finish.setText(_translate("MainWindow", "FINISH"))
        self.text_total_numb.setText(_translate("MainWindow", "Nombre total"))
        self.text_p.setText(_translate("MainWindow", "Plastique"))
        self.text_c.setText(_translate("MainWindow", "Canette"))
        self.time.setText(_translate("MainWindow", "21-04-2022 15:02 "))


from .resources import *
