# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(940, 560))
        self.styleSheet = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.styleSheet.setFont(font)
        self.styleSheet.setStyleSheet("/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"EZOUAGH YOUNESS\n"
"SET APP STYLESHEET - FULL STYLES\n"
"///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"\n"
"QWidget{\n"
"    color: rgb(221, 221, 221);\n"
"    font: 10pt \"Segoe UI\";\n"
"    }\n"
"    \n"
"    #topMenu .QPushButton, QToolTip,#bottomMenu .QPushButton, #toggleButton, #extraTopMenu .QPushButton,#contentSettings .QPushButton{\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    text-align: left;\n"
"    }\n"
"    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"    Bg App */\n"
"    #bgApp {\n"
"    background-color: rgb(255, 255, 255);\n"
"    }\n"
"    \n"
"    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"    Left Menu */\n"
"    #leftMenuBg {\n"
"    background-color:  rgb(61, 61, 61);\n"
"    border-radius:10px;\n"
"    margin:6px;\n"
"    }\n"
"    #topLogo {\n"
"    border-image: url(:/images/images/images/senda-track-logo.png) 0 0 0 0 stretch stretch;\n"
"    \n"
"    }\n"
"    #titleLeftApp { font: 63 12pt \"Segoe UI Semibold\"; }\n"
"    #titleLeftDescription { font: 8pt \"Segoe UI\"; color: rgb(49, 189, 255); }\n"
"    #label_camera_result1\n"
"    { font: 25pt \"Segoe UI\"; color:rgb(0, 255, 0); }\n"
"    #result_frame_camera2  .QLabel\n"
"    { font: 40pt \"Segoe UI\"; color: rgb(49, 189, 255); }\n"
"    /* MENUS */\n"
"    #topMenu .QPushButton,#bottomMenu .QPushButton,#toggleButton {\n"
"    background-color: rgba(44, 49, 58, 255);\n"
"    border: 1px solid rgba(44, 49, 58, 200);\n"
"    border-left: 5px solid rgba(40, 40, 58, 255);\n"
"    border-radius:6px;\n"
"    margin:6px;\n"
"    margin-left:8px;\n"
"    padding-left: 90px;\n"
"    }\n"
"    #topMenu .QPushButton:hover {\n"
"    background-color: rgb(0, 110, 201);\n"
"    }\n"
"    #topMenu .QPushButton:pressed {\n"
"    background-color:  rgb(49, 189, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"    #bottomMenu .QPushButton:hover {\n"
"    background-color:  rgb(0, 110, 201);\n"
"    }\n"
"    #bottomMenu .QPushButton:pressed {\n"
"    background-color:  rgb(49, 189, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"    #leftMenuFrame{\n"
"    border-top: 2px solid rgb(49, 189, 255);\n"
"    }\n"
"    \n"
"    /* Title Menu */\n"
"    #titleRightInfo {color:#fff; padding-left: 10px; }\n"
"    \n"
"    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"    Extra Tab */\n"
"    #extraTopBg , #extraLeftBox{\n"
"    background-color: rgb(50, 57, 63);\n"
"    border: 2px groove rgba(68, 71, 77, 0.74);\n"
"    border-radius:10px;\n"
"    margin:6px;\n"
"    }\n"
"    #extraTopBg{\n"
"    background-color: rgb(49, 189, 255);\n"
"    margin:1px;\n"
"    }\n"
"    \n"
"    /* Icon */\n"
"    #extraIcon {\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-image: url(:/icons/images/icons/about.png);\n"
"    }\n"
"    \n"
"    /* Label */\n"
"    #extraLabel { color: rgb(255, 255, 255); }\n"
"    \n"
"    /* Btn Close */\n"
"    #extraCloseColumnBtn { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"    #extraCloseColumnBtn:hover { background-color: rgb(196, 161, 249); border-style: solid; border-radius: 4px; }\n"
"    #extraCloseColumnBtn:pressed { background-color: rgb(180, 141, 238); border-style: solid; border-radius: 4px; }\n"
"    \n"
"    /* Extra Content */\n"
"    #extraContent{\n"
"    border-top: 3px solid rgba(83, 85, 90, 0.74);\n"
"    }\n"
"    \n"
"    /* Extra Top Menus */\n"
"    #extraTopMenu .QPushButton {\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color:transparent;\n"
"    padding-left: 44px;\n"
"    }\n"
"    #extraTopMenu .QPushButton:hover {\n"
"    background-color: rgb(0, 164, 240);\n"
"    }\n"
"    #extraTopMenu .QPushButton:pressed {\n"
"    background-color: rgb(49, 189, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"    \n"
"    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"    Content App */\n"
"    \n"
"    #contentTopBg{\n"
"    background-color: rgb(61, 61, 61);\n"
"    border-radius:10px;\n"
"    margin:5px;\n"
"    }\n"
"    #contentBottom{\n"
"    border-top: 2px solid rgba(0, 0, 0, 0.363);\n"
"    }\n"
"    \n"
"    /* Top Buttons */\n"
"    #rightButtons .QPushButton { background-color: rgba(44, 49, 58, 255); border: none;  border-radius: 5px; }\n"
"    #rightButtons .QPushButton:hover { background-color: rgba(44, 49, 58, 200); border-style: solid; border-radius: 4px; }\n"
"    #rightButtons .QPushButton:pressed { background-color: rgba(44, 49, 58, 100); border-style: solid; border-radius: 4px; }\n"
"    \n"
"    \n"
"    /* Bottom Bar */\n"
"    #bottomBar { background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(255, 0, 255, 6), stop:1 rgba(44, 49, 58, 255)); }\n"
"    #bottomBar QLabel { font-size: 11px; color: rgba(36, 36, 36, 35); padding-left: 10px; padding-right: 10px; padding-bottom: 2px; }\n"
"    \n"
"    /* CONTENT SETTINGS */\n"
"    /* MENUS */\n"
"    #contentSettings .QPushButton {\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color:transparent;\n"
"    padding-left: 44px;\n"
"    }\n"
"    #contentSettings .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"    }\n"
"    #contentSettings .QPushButton:pressed {\n"
"    background-color: rgb(49, 189, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"    RadioButton */\n"
"    QRadioButton{\n"
"    font: 42pt \"Segoe UI\"; color: rgb(49, 189, 255);\n"
"    }\n"
"    QRadioButton::indicator {\n"
"    border:6px solid rgb(58, 66, 81);\n"
"    width: 30px;\n"
"    height: 30px;\n"
"    margin-right: 20px;\n"
"    border-radius: 20px;\n"
"    background: rgb(171, 171, 171);\n"
"    }\n"
"    QRadioButton::indicator:hover {\n"
"    border: 6px solid rgb(49, 189, 255);\n"
"    }\n"
"    QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(49, 189, 255);\n"
"    border: 4px solid rgb(52, 59, 72);\n"
"    }\n"
"    \n"
"    \n"
"    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"    Button */\n"
"    #pagesContainer QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(52, 59, 72);\n"
"    }\n"
"    #pagesContainer QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"    }\n"
"    #pagesContainer QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    }\n")
        self.styleSheet.setObjectName("styleSheet")
        self.appMargins = QtWidgets.QVBoxLayout(self.styleSheet)
        self.appMargins.setContentsMargins(2, 2, 2, 2)
        self.appMargins.setSpacing(0)
        self.appMargins.setObjectName("appMargins")
        self.bgApp = QtWidgets.QFrame(self.styleSheet)
        self.bgApp.setStyleSheet("")
        self.bgApp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bgApp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bgApp.setObjectName("bgApp")
        self.appLayout = QtWidgets.QHBoxLayout(self.bgApp)
        self.appLayout.setContentsMargins(0, 0, 0, 0)
        self.appLayout.setSpacing(0)
        self.appLayout.setObjectName("appLayout")
        self.leftMenuBg = QtWidgets.QFrame(self.bgApp)
        self.leftMenuBg.setEnabled(True)
        self.leftMenuBg.setMinimumSize(QtCore.QSize(60, 0))
        self.leftMenuBg.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leftMenuBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuBg.setObjectName("leftMenuBg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftMenuBg)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topLogoInfo = QtWidgets.QFrame(self.leftMenuBg)
        self.topLogoInfo.setMinimumSize(QtCore.QSize(0, 50))
        self.topLogoInfo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.topLogoInfo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topLogoInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLogoInfo.setObjectName("topLogoInfo")
        self.topLogo = QtWidgets.QFrame(self.topLogoInfo)
        self.topLogo.setGeometry(QtCore.QRect(2, 5, 42, 42))
        self.topLogo.setMinimumSize(QtCore.QSize(42, 42))
        self.topLogo.setMaximumSize(QtCore.QSize(42, 42))
        self.topLogo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLogo.setObjectName("topLogo")
        self.titleLeftApp = QtWidgets.QLabel(self.topLogoInfo)
        self.titleLeftApp.setGeometry(QtCore.QRect(70, 8, 160, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.titleLeftApp.setFont(font)
        self.titleLeftApp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.titleLeftApp.setObjectName("titleLeftApp")
        self.titleLeftDescription = QtWidgets.QLabel(self.topLogoInfo)
        self.titleLeftDescription.setGeometry(QtCore.QRect(70, 27, 160, 16))
        self.titleLeftDescription.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleLeftDescription.setFont(font)
        self.titleLeftDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.titleLeftDescription.setObjectName("titleLeftDescription")
        self.verticalLayout_3.addWidget(self.topLogoInfo)
        self.leftMenuFrame = QtWidgets.QFrame(self.leftMenuBg)
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalMenuLayout = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalMenuLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalMenuLayout.setSpacing(0)
        self.verticalMenuLayout.setObjectName("verticalMenuLayout")
        self.toggleBox = QtWidgets.QFrame(self.leftMenuFrame)
        self.toggleBox.setMaximumSize(QtCore.QSize(16777215, 45))
        self.toggleBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toggleBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toggleBox.setObjectName("toggleBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.toggleBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalMenuLayout.addWidget(self.toggleBox)
        self.topMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.topMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topMenu.setFrameShadow(QtWidgets.QFrame.Plain)
        self.topMenu.setObjectName("topMenu")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.topMenu)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_home = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_home.sizePolicy().hasHeightForWidth())
        self.btn_home.setSizePolicy(sizePolicy)
        self.btn_home.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_home.setFont(font)
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_home.setStyleSheet("background-image:url(:/icons/images/icons/cil-user.png);")
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout_8.addWidget(self.btn_home)
        self.btn_admin = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_admin.sizePolicy().hasHeightForWidth())
        self.btn_admin.setSizePolicy(sizePolicy)
        self.btn_admin.setMinimumSize(QtCore.QSize(0, 45))
        self.btn_admin.setFont(font)
        self.btn_admin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_admin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_admin.setStyleSheet("background-image: url(:/icons/images/icons/cil-settings.png);")
        self.btn_admin.setObjectName("btn_admin")
        self.verticalLayout_8.addWidget(self.btn_admin)
        self.btn_exit = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_exit.sizePolicy().hasHeightForWidth())
        self.btn_exit.setSizePolicy(sizePolicy)
        self.btn_exit.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_exit.setFont(font)
        self.btn_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_exit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_exit.setStyleSheet("background-image: url(:/icons/images/icons/cil-power-standby.png);")
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout_8.addWidget(self.btn_exit)
        self.verticalMenuLayout.addWidget(self.topMenu, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.leftMenuFrame)
        self.appLayout.addWidget(self.leftMenuBg)
        self.contentBox = QtWidgets.QFrame(self.bgApp)
        self.contentBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentTopBg = QtWidgets.QFrame(self.contentBox)
        self.contentTopBg.setMinimumSize(QtCore.QSize(0, 50))
        self.contentTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.contentTopBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTopBg.setObjectName("contentTopBg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBg)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBox = QtWidgets.QFrame(self.contentTopBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBox.sizePolicy().hasHeightForWidth())
        self.leftBox.setSizePolicy(sizePolicy)
        self.leftBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBox.setObjectName("leftBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.leftBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titleRightInfo = QtWidgets.QLabel(self.leftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleRightInfo.sizePolicy().hasHeightForWidth())
        self.titleRightInfo.setSizePolicy(sizePolicy)
        self.titleRightInfo.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleRightInfo.setFont(font)
        self.titleRightInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleRightInfo.setObjectName("titleRightInfo")
        self.horizontalLayout_3.addWidget(self.titleRightInfo)
        self.horizontalLayout.addWidget(self.leftBox)
        self.rightButtons = QtWidgets.QFrame(self.contentTopBg)
        self.rightButtons.setMinimumSize(QtCore.QSize(0, 28))
        self.rightButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightButtons.setObjectName("rightButtons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rightButtons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimizeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeAppBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeAppBtn.setIcon(icon)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_2.addWidget(self.minimizeAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeAppBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeAppBtn.setIcon(icon1)
        self.closeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_2.addWidget(self.closeAppBtn)
        self.horizontalLayout.addWidget(self.rightButtons, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.contentTopBg)
        self.contentBottom = QtWidgets.QFrame(self.contentBox)
        self.contentBottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBottom.setObjectName("contentBottom")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.contentBottom)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.content = QtWidgets.QFrame(self.contentBottom)
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Plain)
        self.content.setObjectName("content")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pagesContainer = QtWidgets.QFrame(self.content)
        self.pagesContainer.setStyleSheet("")
        self.pagesContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pagesContainer.setFrameShadow(QtWidgets.QFrame.Plain)
        self.pagesContainer.setObjectName("pagesContainer")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.pagesContainer)
        self.verticalLayout_15.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.stackedWidget = QtWidgets.QStackedWidget(self.pagesContainer)
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setStyleSheet("")
        self.home_page.setObjectName("home_page")
        self.frame_2 = QtWidgets.QFrame(self.home_page)
        self.frame_2.setGeometry(QtCore.QRect(10, 0, 1131, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.user_frame_all = QtWidgets.QFrame(self.frame_2)
        self.user_frame_all.setGeometry(QtCore.QRect(0, 0, 1100, 520))
        self.user_frame_all.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.user_frame_all.setFrameShadow(QtWidgets.QFrame.Plain)
        self.user_frame_all.setObjectName("user_frame_all")
        self.result_frame_camera2 = QtWidgets.QFrame(self.user_frame_all)
        self.result_frame_camera2.setGeometry(QtCore.QRect(520, 0, 420, 480))
        self.result_frame_camera2.setStyleSheet("#result_frame_camera{background-color:rgba(0, 22, 72,35);border-radius:4px;}")
        self.result_frame_camera2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.result_frame_camera2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.result_frame_camera2.setObjectName("result_frame_camera2")
        self.label_camera_result2_1 = QtWidgets.QLabel(self.result_frame_camera2)
        self.label_camera_result2_1.setGeometry(QtCore.QRect(200, 80, 200, 65))
        self.label_camera_result2_1.setLineWidth(1)
        self.label_camera_result2_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_camera_result2_1.setObjectName("label_camera_result2_1")
        self.label_camera_result2_2 = QtWidgets.QLabel(self.result_frame_camera2)
        self.label_camera_result2_2.setGeometry(QtCore.QRect(200, 180, 200, 65))
        self.label_camera_result2_2.setLineWidth(1)
        self.label_camera_result2_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_camera_result2_2.setObjectName("label_camera_result2_2")
        self.label_camera_result2_3 = QtWidgets.QLabel(self.result_frame_camera2)
        self.label_camera_result2_3.setGeometry(QtCore.QRect(200, 280, 200, 65))
        self.label_camera_result2_3.setLineWidth(1)
        self.label_camera_result2_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_camera_result2_3.setObjectName("label_camera_result2_3")
        self.label_camera_result2_4 = QtWidgets.QLabel(self.result_frame_camera2)
        self.label_camera_result2_4.setGeometry(QtCore.QRect(200, 380, 200, 65))
        self.label_camera_result2_4.setLineWidth(1)
        self.label_camera_result2_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_camera_result2_4.setObjectName("label_camera_result2_4")
        self.label_camera_result2_5 = QtWidgets.QLabel(self.result_frame_camera2)
        self.label_camera_result2_5.setGeometry(QtCore.QRect(0, 0, 410, 61))
        self.label_camera_result2_5.setStyleSheet("#label_camera_result2_5\n"
"    { font: 25pt \"Segoe UI\"; color:rgb(0, 255, 0); }")
        self.label_camera_result2_5.setLineWidth(1)
        self.label_camera_result2_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_camera_result2_5.setObjectName("label_camera_result2_5")
        self.label_camera_result2_6 = QtWidgets.QLabel(self.result_frame_camera2)
        self.label_camera_result2_6.setGeometry(QtCore.QRect(0, 80, 200, 65))
        self.label_camera_result2_6.setLineWidth(1)
        self.label_camera_result2_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_camera_result2_6.setObjectName("label_camera_result2_6")
        self.label_camera_result2_7 = QtWidgets.QLabel(self.result_frame_camera2)
        self.label_camera_result2_7.setGeometry(QtCore.QRect(0, 180, 200, 65))
        self.label_camera_result2_7.setLineWidth(1)
        self.label_camera_result2_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_camera_result2_7.setObjectName("label_camera_result2_7")
        self.label_camera_result2_8 = QtWidgets.QLabel(self.result_frame_camera2)
        self.label_camera_result2_8.setGeometry(QtCore.QRect(0, 280, 200, 65))
        self.label_camera_result2_8.setLineWidth(1)
        self.label_camera_result2_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_camera_result2_8.setObjectName("label_camera_result2_8")
        self.label_camera_result2_9 = QtWidgets.QLabel(self.result_frame_camera2)
        self.label_camera_result2_9.setGeometry(QtCore.QRect(0, 380, 200, 65))
        self.label_camera_result2_9.setLineWidth(1)
        self.label_camera_result2_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_camera_result2_9.setObjectName("label_camera_result2_9")
        self.image_frame_camera2 = QtWidgets.QFrame(self.user_frame_all)
        self.image_frame_camera2.setGeometry(QtCore.QRect(10, 0, 480, 480))
        self.image_frame_camera2.setStyleSheet("#image_frame_camera2{background-color:rgba(0, 22, 72,35);border-radius:4px;}")
        self.image_frame_camera2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.image_frame_camera2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.image_frame_camera2.setObjectName("image_frame_camera2")
        self.label_camera_image2 = QtWidgets.QLabel(self.image_frame_camera2)
        self.label_camera_image2.setGeometry(QtCore.QRect(0, 0, 480, 480))
        self.label_camera_image2.setLineWidth(1)
        self.label_camera_image2.setScaledContents(True)
        self.label_camera_image2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_camera_image2.setObjectName("label_camera_image2")
        self.stackedWidget.addWidget(self.home_page)
        self.admin_page = QtWidgets.QWidget()
        self.admin_page.setStyleSheet("")
        self.admin_page.setObjectName("admin_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.admin_page)
        self.verticalLayout.setContentsMargins(10, 0, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_1 = QtWidgets.QFrame(self.admin_page)
        self.frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_1.setObjectName("frame_1")
        self.admin_frame_all = QtWidgets.QFrame(self.frame_1)
        self.admin_frame_all.setGeometry(QtCore.QRect(0, 0, 1100, 520))
        self.admin_frame_all.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.admin_frame_all.setFrameShadow(QtWidgets.QFrame.Plain)
        self.admin_frame_all.setObjectName("admin_frame_all")
        self.result_frame_camera1 = QtWidgets.QFrame(self.admin_frame_all)
        self.result_frame_camera1.setGeometry(QtCore.QRect(520, 0, 420, 480))
        self.result_frame_camera1.setStyleSheet("#result_frame_camera{background-color:rgba(0, 22, 72,35);border-radius:4px;}")
        self.result_frame_camera1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.result_frame_camera1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.result_frame_camera1.setObjectName("result_frame_camera1")
        self.label_camera_result1 = QtWidgets.QLabel(self.result_frame_camera1)
        self.label_camera_result1.setGeometry(QtCore.QRect(0, 0, 421, 50))
        self.label_camera_result1.setLineWidth(1)
        self.label_camera_result1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_camera_result1.setObjectName("label_camera_result1")
        self.radioButton_cam_plastic1 = QtWidgets.QRadioButton(self.result_frame_camera1)
        self.radioButton_cam_plastic1.setGeometry(QtCore.QRect(0, 80, 300, 50))
        self.radioButton_cam_plastic1.setObjectName("radioButton_cam_plastic1")
        self.radioButton_cam_metal1 = QtWidgets.QRadioButton(self.result_frame_camera1)
        self.radioButton_cam_metal1.setGeometry(QtCore.QRect(0, 180, 300, 50))
        self.radioButton_cam_metal1.setObjectName("radioButton_cam_metal1")
        self.radioButton_cam_glass1 = QtWidgets.QRadioButton(self.result_frame_camera1)
        self.radioButton_cam_glass1.setGeometry(QtCore.QRect(0, 280, 300, 50))
        self.radioButton_cam_glass1.setObjectName("radioButton_cam_glass1")
        self.radioButton_cam_other1 = QtWidgets.QRadioButton(self.result_frame_camera1)
        self.radioButton_cam_other1.setGeometry(QtCore.QRect(0, 380, 300, 50))
        self.radioButton_cam_other1.setObjectName("radioButton_cam_other1")
        self.image_frame_camera1 = QtWidgets.QFrame(self.admin_frame_all)
        self.image_frame_camera1.setGeometry(QtCore.QRect(10, 0, 480, 480))
        self.image_frame_camera1.setStyleSheet("#image_frame_camera1 {background-color:rgba(0, 22, 72,35);border-radius:4px;}")
        self.image_frame_camera1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.image_frame_camera1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.image_frame_camera1.setObjectName("image_frame_camera1")
        self.label_camera_image1 = QtWidgets.QLabel(self.image_frame_camera1)
        self.label_camera_image1.setGeometry(QtCore.QRect(0, 0, 480, 480))
        self.label_camera_image1.setScaledContents(True)
        self.label_camera_image1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_camera_image1.setObjectName("label_camera_image1")
        self.verticalLayout.addWidget(self.frame_1)
        self.stackedWidget.addWidget(self.admin_page)
        self.verticalLayout_15.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.pagesContainer)
        self.verticalLayout_6.addWidget(self.content)
        self.bottomBar = QtWidgets.QFrame(self.contentBottom)
        self.bottomBar.setMinimumSize(QtCore.QSize(0, 22))
        self.bottomBar.setMaximumSize(QtCore.QSize(16777215, 22))
        self.bottomBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomBar.setObjectName("bottomBar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.bottomBar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.creditsLabel = QtWidgets.QLabel(self.bottomBar)
        self.creditsLabel.setMaximumSize(QtCore.QSize(16777215, 16))
        self.creditsLabel.setText("By: EZOUAGH YOUNESS")
        self.creditsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.creditsLabel.setObjectName("creditsLabel")
        self.horizontalLayout_5.addWidget(self.creditsLabel)
        self.version = QtWidgets.QLabel(self.bottomBar)
        self.version.setStyleSheet("color:#fff;")
        self.version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version.setObjectName("version")
        self.horizontalLayout_5.addWidget(self.version)
        self.frame_size_grip = QtWidgets.QFrame(self.bottomBar)
        self.frame_size_grip.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_5.addWidget(self.frame_size_grip)
        self.verticalLayout_6.addWidget(self.bottomBar)
        self.verticalLayout_2.addWidget(self.contentBottom)
        self.appLayout.addWidget(self.contentBox)
        self.appMargins.addWidget(self.bgApp)
        MainWindow.setCentralWidget(self.styleSheet)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLeftApp.setText(_translate("MainWindow", "IOSEN"))
        self.titleLeftDescription.setText(_translate("MainWindow", "EZOUAGH YOUNESS"))
        self.btn_home.setText(_translate("MainWindow", "Home"))
        self.btn_admin.setText(_translate("MainWindow", "Admin"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))
        self.titleRightInfo.setText(_translate("MainWindow", "IOSEN"))
        self.label_camera_result2_1.setText(_translate("MainWindow", " : 0"))
        self.label_camera_result2_2.setText(_translate("MainWindow", " : 0"))
        self.label_camera_result2_3.setText(_translate("MainWindow", " : 0"))
        self.label_camera_result2_4.setText(_translate("MainWindow", " : 0"))
        self.label_camera_result2_5.setText(_translate("MainWindow", "Waiting for an Object!..."))
        self.label_camera_result2_6.setText(_translate("MainWindow", "Plastic"))
        self.label_camera_result2_7.setText(_translate("MainWindow", "Metal"))
        self.label_camera_result2_8.setText(_translate("MainWindow", "Glass"))
        self.label_camera_result2_9.setText(_translate("MainWindow", "Other"))
        self.label_camera_result1.setText(_translate("MainWindow", "Waiting for an Object!..."))
        self.radioButton_cam_plastic1.setText(_translate("MainWindow", "Plastic"))
        self.radioButton_cam_metal1.setText(_translate("MainWindow", "Metal"))
        self.radioButton_cam_glass1.setText(_translate("MainWindow", "Glass"))
        self.radioButton_cam_other1.setText(_translate("MainWindow", "Other"))
        self.version.setText(_translate("MainWindow", "v1.0.1"))
from .resources import *