# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pano.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        font = QtGui.QFont()
        font.setUnderline(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("\n"
"/*////////////// Initial start page/////////////////*/\n"
"#page{background:url(:/background_img/images/images/bg1.png);}\n"
"\n"
"#btn_start{border: 0px solid #666;\n"
"font: 25 20pt \"Piboto Condensed\";\n"
"color:white;\n"
"}\n"
"\n"
"#btn_help_1 {border-radius: 20px;border: 2px solid #666;font: 25 20pt \"Piboto Condensed\";color:#737373;}\n"
"\n"
"#time_3{font: 25 15pt \"Piboto Condensed\";\n"
"color:#737373;\n"
"}\n"
"\n"
"/*///////////////// Scan Qr code page/////////////////////*/\n"
"#main_page {background-image:url(:/background_img/images/images/bg2.png);}\n"
"\n"
"#time_2{font: 25 15pt \"Piboto Condensed\";\n"
"color:white;\n"
"}\n"
"\n"
"#text_message{color:#737373;\n"
"font: 25 15pt \"Piboto Condensed\";\n"
"}\n"
"\n"
"#btn_restart{\n"
"border-radius: 30px;\n"
"border: 0px solid white;\n"
"font: 25 20pt \"Piboto Condensed\";\n"
"color:white;\n"
"}\n"
"\n"
"#btn_help_3 , #btn_finish {\n"
"border-radius: 20px;\n"
"border: 2px solid #666;\n"
"font: 25 20pt \"Piboto Condensed\";\n"
"color:#737373;\n"
"}\n"
"\n"
"#btn_finish {\n"
"color:white;\n"
"border: 0px solid white;\n"
"font: 25 17pt \"Piboto Condensed\";\n"
"}\n"
"\n"
"#btn_refresh {\n"
"border-radius: 30px;\n"
"border: 0px solid #666;\n"
"}\n"
"\n"
"/*////////////////////// Counting page ///////////////////////////////*/\n"
"\n"
"#page_content {background-image:url(:/background_img/images/images/bg.png);\n"
"background-color:black;\n"
"background-origin: cover;\n"
"background-clip: padding;\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"}\n"
"\n"
"#text_p , #text_c {color:white}\n"
"\n"
"#number_c, #number_p , #total_number ,#text_total_numb ,#text_u1 ,#number_un,#text_u2,#time_1 {color:#737373;}\n"
"\n"
"#btn_echanger , #butt_help{color:#737373;}\n"
"\n"
"#btn_echanger, #total_number{border-radius: 55px;border: 2px solid #666;}\n"
"\n"
"#butt_help {border-radius: 20px;border: 2px solid #666;font: 25 20pt \"Piboto Condensed\"}\n"
"\n"
"#btn_echanger:hover , #butt_help:hover ,#btn_echanger:pressed , #butt_help:pressed {\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.306818 rgba(0, 0, 0, 5), stop:0.653409 rgba(0, 0, 0, 14), stop:0.926136 rgba(0, 0, 0, 30))\n"
"}\n"
"\n"
"#number_p{font: 45pt \"Piboto Condensed\";}\n"
"#number_c {font: 45pt \"Piboto Condensed\";}\n"
"\n"
"#total_number{font: 25 40pt \"Piboto Condensed\";}\n"
"#btn_echanger{font: 25 14pt \"Piboto Condensed\";}\n"
"\n"
"#text_p , #text_c {font: 25 20pt \"Piboto Condensed\";}\n"
"#text_total_numb{font: 15 16pt \"Piboto Condensed\";}\n"
"\n"
"#level_c , #level_p{\n"
"    border: 1px solid grey;\n"
"    border-radius: 2px;\n"
"    }\n"
"#level_p::chunk , #level_c::chunk{\n"
"background-color: rgb(0, 255, 0);\n"
"width: 8px;\n"
"}\n"
"\n"
"#time_1{font: 25 15pt \"Piboto Condensed\";}\n"
"\n"
"#text_u1 ,#text_u2{font: 25 10pt \"Piboto Condensed\";}\n"
"#number_un{font: 25 15pt\"Piboto Condensed\";}\n"
"#text_u1 ,#number_un,#text_u2 {color:rgb(103, 103, 103);}")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.qr_image = QtWidgets.QLabel(self.main_page)
        self.qr_image.setGeometry(QtCore.QRect(352, 100, 320, 320))
        self.qr_image.setText("")
        self.qr_image.setAlignment(QtCore.Qt.AlignCenter)
        self.qr_image.setObjectName("qr_image")
        self.text_message = QtWidgets.QLabel(self.main_page)
        self.text_message.setGeometry(QtCore.QRect(0, 40, 1024, 41))
        self.text_message.setAlignment(QtCore.Qt.AlignCenter)
        self.text_message.setObjectName("text_message")
        self.time_2 = QtWidgets.QLabel(self.main_page)
        self.time_2.setGeometry(QtCore.QRect(0, 5, 1024, 29))
        self.time_2.setAlignment(QtCore.Qt.AlignCenter)
        self.time_2.setObjectName("time_2")
        self.btn_restart = QtWidgets.QPushButton(self.main_page)
        self.btn_restart.setGeometry(QtCore.QRect(414, 510, 200, 61))
        self.btn_restart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_restart.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_restart.setObjectName("btn_restart")
        self.btn_help_3 = QtWidgets.QPushButton(self.main_page)
        self.btn_help_3.setGeometry(QtCore.QRect(27, 535, 40, 40))
        self.btn_help_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_help_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_help_3.setObjectName("btn_help_3")
        self.btn_finish = QtWidgets.QPushButton(self.main_page)
        self.btn_finish.setGeometry(QtCore.QRect(403, 440, 151, 40))
        self.btn_finish.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_finish.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_finish.setObjectName("btn_finish")
        self.btn_refresh = QtWidgets.QPushButton(self.main_page)
        self.btn_refresh.setGeometry(QtCore.QRect(580, 441, 35, 35))
        self.btn_refresh.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_refresh.setText("")
        self.btn_refresh.setObjectName("btn_refresh")
        self.stackedWidget.addWidget(self.main_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.btn_start = QtWidgets.QPushButton(self.page)
        self.btn_start.setGeometry(QtCore.QRect(409, 430, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Piboto Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.btn_start.setFont(font)
        self.btn_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_start.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_start.setObjectName("btn_start")
        self.btn_help_1 = QtWidgets.QPushButton(self.page)
        self.btn_help_1.setGeometry(QtCore.QRect(27, 535, 40, 40))
        self.btn_help_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_help_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_help_1.setObjectName("btn_help_1")
        self.time_3 = QtWidgets.QLabel(self.page)
        self.time_3.setGeometry(QtCore.QRect(0, 5, 1024, 29))
        self.time_3.setAlignment(QtCore.Qt.AlignCenter)
        self.time_3.setObjectName("time_3")
        self.stackedWidget.addWidget(self.page)
        self.countingPage = QtWidgets.QWidget()
        self.countingPage.setObjectName("countingPage")
        self.page_content = QtWidgets.QFrame(self.countingPage)
        self.page_content.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.page_content.setObjectName("page_content")
        self.total_number = QtWidgets.QLabel(self.page_content)
        self.total_number.setGeometry(QtCore.QRect(460, 132, 110, 110))
        font = QtGui.QFont()
        font.setFamily("Piboto Condensed")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.total_number.setFont(font)
        self.total_number.setAlignment(QtCore.Qt.AlignCenter)
        self.total_number.setObjectName("total_number")
        self.text_total_numb = QtWidgets.QLabel(self.page_content)
        self.text_total_numb.setGeometry(QtCore.QRect(410, 90, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Piboto Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(1)
        self.text_total_numb.setFont(font)
        self.text_total_numb.setAlignment(QtCore.Qt.AlignCenter)
        self.text_total_numb.setObjectName("text_total_numb")
        self.text_u1 = QtWidgets.QLabel(self.page_content)
        self.text_u1.setGeometry(QtCore.QRect(406, 280, 100, 21))
        self.text_u1.setObjectName("text_u1")
        self.time_1 = QtWidgets.QLabel(self.page_content)
        self.time_1.setGeometry(QtCore.QRect(0, 5, 1024, 29))
        self.time_1.setAlignment(QtCore.Qt.AlignCenter)
        self.time_1.setObjectName("time_1")
        self.number_un = QtWidgets.QLabel(self.page_content)
        self.number_un.setGeometry(QtCore.QRect(499, 280, 31, 21))
        self.number_un.setAlignment(QtCore.Qt.AlignCenter)
        self.number_un.setObjectName("number_un")
        self.butt_help = QtWidgets.QPushButton(self.page_content)
        self.butt_help.setGeometry(QtCore.QRect(27, 535, 40, 40))
        self.butt_help.setFocusPolicy(QtCore.Qt.NoFocus)
        self.butt_help.setObjectName("butt_help")
        self.number_p = QtWidgets.QLabel(self.page_content)
        self.number_p.setGeometry(QtCore.QRect(665, 400, 180, 70))
        font = QtGui.QFont()
        font.setFamily("Piboto Condensed")
        font.setPointSize(45)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.number_p.setFont(font)
        self.number_p.setAlignment(QtCore.Qt.AlignCenter)
        self.number_p.setObjectName("number_p")
        self.level_p = QtWidgets.QProgressBar(self.page_content)
        self.level_p.setGeometry(QtCore.QRect(816, 86, 36, 17))
        self.level_p.setProperty("value", 0)
        self.level_p.setTextVisible(False)
        self.level_p.setObjectName("level_p")
        self.level_c = QtWidgets.QProgressBar(self.page_content)
        self.level_c.setGeometry(QtCore.QRect(331, 86, 36, 17))
        self.level_c.setProperty("value", 50)
        self.level_c.setTextVisible(False)
        self.level_c.setObjectName("level_c")
        self.text_p = QtWidgets.QLabel(self.page_content)
        self.text_p.setGeometry(QtCore.QRect(655, 120, 200, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.text_p.setFont(font)
        self.text_p.setObjectName("text_p")
        self.text_u2 = QtWidgets.QLabel(self.page_content)
        self.text_u2.setGeometry(QtCore.QRect(535, 280, 90, 21))
        self.text_u2.setObjectName("text_u2")
        self.number_c = QtWidgets.QLabel(self.page_content)
        self.number_c.setGeometry(QtCore.QRect(180, 400, 180, 70))
        font = QtGui.QFont()
        font.setFamily("Piboto Condensed")
        font.setPointSize(45)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.number_c.setFont(font)
        self.number_c.setAlignment(QtCore.Qt.AlignCenter)
        self.number_c.setObjectName("number_c")
        self.text_c = QtWidgets.QLabel(self.page_content)
        self.text_c.setGeometry(QtCore.QRect(168, 120, 200, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.text_c.setFont(font)
        self.text_c.setObjectName("text_c")
        self.btn_echanger = QtWidgets.QPushButton(self.page_content)
        self.btn_echanger.setGeometry(QtCore.QRect(460, 400, 110, 110))
        font = QtGui.QFont()
        font.setFamily("Piboto Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.btn_echanger.setFont(font)
        self.btn_echanger.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_echanger.setObjectName("btn_echanger")
        self.stackedWidget.addWidget(self.countingPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text_message.setText(_translate("MainWindow", "Scanner le Qr code suivant pour finir la procédure "))
        self.time_2.setText(_translate("MainWindow", "21-04-2022 15:02 "))
        self.btn_restart.setText(_translate("MainWindow", "Recommencer"))
        self.btn_help_3.setText(_translate("MainWindow", "?"))
        self.btn_finish.setText(_translate("MainWindow", "Terminer (60)"))
        self.btn_start.setText(_translate("MainWindow", "Commencer"))
        self.btn_help_1.setText(_translate("MainWindow", "?"))
        self.time_3.setText(_translate("MainWindow", "21-04-2022 15:02 "))
        self.total_number.setText(_translate("MainWindow", "0"))
        self.text_total_numb.setText(_translate("MainWindow", "Nombre total"))
        self.text_u1.setText(_translate("MainWindow", "You have inserted"))
        self.time_1.setText(_translate("MainWindow", "21-04-2022 15:02 "))
        self.number_un.setText(_translate("MainWindow", "0"))
        self.butt_help.setText(_translate("MainWindow", "?"))
        self.number_p.setText(_translate("MainWindow", "0"))
        self.text_p.setText(_translate("MainWindow", "Plastique"))
        self.text_u2.setText(_translate("MainWindow", "unkown objects"))
        self.number_c.setText(_translate("MainWindow", "0"))
        self.text_c.setText(_translate("MainWindow", "Canette"))
        self.btn_echanger.setText(_translate("MainWindow", "ÉCHANGER"))
from .resources import *
