# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(738, 1284)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("/*////////////////////////// Counting page /////////////////////////////*/\n"
"#counting_page {background-image:url(:/images/images/images/menu.png);\n"
"background-color:black;\n"
"background-origin: cover;\n"
"background-clip: padding;\n"
"background-position: center;\n"
"background-repeat: no-repeat;}\n"
"\n"
"#btn_help {border-radius: 20px;border: 2px solid #666;font: 25 20pt \"Piboto Condensed\" ;color:#737373;}\n"
"\n"
"#level_c , #level_p{\n"
"backgroundcolor:rgba(0,0,0,0);\n"
"border: 1px solid grey;\n"
"border-radius: 2px;\n"
"}\n"
"#level_p::chunk , #level_c::chunk{\n"
"background-color: rgb(0, 255, 0);\n"
"width: 8px;\n"
"}\n"
"\n"
"#number_c, #number_p {color:#737373;}\n"
"#number_p , #number_c{font: 45pt \"Piboto Condensed\";}\n"
"\n"
"#number_un{color:#737373;font: 25 15pt\"Piboto Condensed\";}\n"
"\n"
"#text_p , #text_c {color:white ;font: 25 20pt \"Piboto Condensed\";}\n"
"#text_total_numb {color:#737373;font: 15 16pt \"Piboto Condensed\";}\n"
"\n"
"#text_u1 ,#text_u2 {color:#737373;font: 25 10pt \"Piboto Condensed\";}\n"
"#text_u1 ,#number_un,#text_u2 {color:rgb(103, 103, 103);}\n"
"\n"
"\n"
"#time_1 {color:#737373;}\n"
"\n"
"#total_number{color:#737373;\n"
"border-radius: 50px;\n"
"border: 2px solid #666\n"
";border-radius: 55px;\n"
"border: 2px solid #666\n"
";font: 25 40pt \"Piboto Condensed\";\n"
"}\n"
"\n"
"#btn_help:hover ,#btn_help:pressed {\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.306818 rgba(0, 0, 0, 5), stop:0.653409 rgba(0, 0, 0, 14), stop:0.926136 rgba(0, 0, 0, 30))\n"
"}\n"
"\n"
"#btn_scanqr , #btn_printer , #btn_donate {border: 0px solid #666;}\n"
"#lbl_donate ,#lbl_printer ,#lbl_scanqr {color:rgb(62, 62, 62); font:20 14pt \"Piboto Condensed\";\n"
"}\n"
"\n"
"#optionstitle{color:rgb(62, 62, 62); font:20 17pt \"Piboto Condensed\";}")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 738, 1284))
        self.stackedWidget.setObjectName("stackedWidget")
        self.counting_page = QtWidgets.QWidget()
        self.counting_page.setObjectName("counting_page")
        self.time_1 = QtWidgets.QLabel(self.counting_page)
        self.time_1.setGeometry(QtCore.QRect(10, 0, 701, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(11)
        self.time_1.setFont(font)
        self.time_1.setAlignment(QtCore.Qt.AlignCenter)
        self.time_1.setObjectName("time_1")
        self.number_p = QtWidgets.QLabel(self.counting_page)
        self.number_p.setGeometry(QtCore.QRect(500, 710, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Piboto Condensed")
        font.setPointSize(45)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.number_p.setFont(font)
        self.number_p.setAlignment(QtCore.Qt.AlignCenter)
        self.number_p.setObjectName("number_p")
        self.number_c = QtWidgets.QLabel(self.counting_page)
        self.number_c.setGeometry(QtCore.QRect(170, 710, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Piboto Condensed")
        font.setPointSize(45)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.number_c.setFont(font)
        self.number_c.setAlignment(QtCore.Qt.AlignCenter)
        self.number_c.setObjectName("number_c")
        self.btn_help = QtWidgets.QPushButton(self.counting_page)
        self.btn_help.setGeometry(QtCore.QRect(40, 1230, 41, 41))
        self.btn_help.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_help.setText("")
        self.btn_help.setObjectName("btn_help")
        self.number_un = QtWidgets.QLabel(self.counting_page)
        self.number_un.setGeometry(QtCore.QRect(360, 290, 31, 21))
        self.number_un.setAlignment(QtCore.Qt.AlignCenter)
        self.number_un.setObjectName("number_un")
        self.text_u1 = QtWidgets.QLabel(self.counting_page)
        self.text_u1.setGeometry(QtCore.QRect(240, 290, 111, 21))
        self.text_u1.setAlignment(QtCore.Qt.AlignCenter)
        self.text_u1.setObjectName("text_u1")
        self.total_number = QtWidgets.QLabel(self.counting_page)
        self.total_number.setGeometry(QtCore.QRect(320, 150, 111, 111))
        font = QtGui.QFont()
        font.setFamily("Piboto Condensed")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.total_number.setFont(font)
        self.total_number.setAlignment(QtCore.Qt.AlignCenter)
        self.total_number.setObjectName("total_number")
        self.text_u2 = QtWidgets.QLabel(self.counting_page)
        self.text_u2.setGeometry(QtCore.QRect(399, 290, 101, 21))
        self.text_u2.setAlignment(QtCore.Qt.AlignCenter)
        self.text_u2.setObjectName("text_u2")
        self.text_p = QtWidgets.QLabel(self.counting_page)
        self.text_p.setGeometry(QtCore.QRect(430, 380, 200, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.text_p.setFont(font)
        self.text_p.setObjectName("text_p")
        self.level_p = QtWidgets.QProgressBar(self.counting_page)
        self.level_p.setGeometry(QtCore.QRect(620, 354, 44, 21))
        self.level_p.setProperty("value", 0)
        self.level_p.setTextVisible(False)
        self.level_p.setObjectName("level_p")
        self.text_c = QtWidgets.QLabel(self.counting_page)
        self.text_c.setGeometry(QtCore.QRect(80, 380, 200, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.text_c.setFont(font)
        self.text_c.setObjectName("text_c")
        self.level_c = QtWidgets.QProgressBar(self.counting_page)
        self.level_c.setGeometry(QtCore.QRect(278, 354, 44, 21))
        self.level_c.setProperty("value", 50)
        self.level_c.setTextVisible(False)
        self.level_c.setObjectName("level_c")
        self.text_total_numb = QtWidgets.QLabel(self.counting_page)
        self.text_total_numb.setGeometry(QtCore.QRect(270, 110, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Piboto Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(1)
        self.text_total_numb.setFont(font)
        self.text_total_numb.setAlignment(QtCore.Qt.AlignCenter)
        self.text_total_numb.setObjectName("text_total_numb")
        self.lbl_scanqr = QtWidgets.QLabel(self.counting_page)
        self.lbl_scanqr.setGeometry(QtCore.QRect(40, 1170, 172, 41))
        self.lbl_scanqr.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_scanqr.setObjectName("lbl_scanqr")
        self.btn_scanqr = QtWidgets.QPushButton(self.counting_page)
        self.btn_scanqr.setGeometry(QtCore.QRect(61, 969, 161, 241))
        self.btn_scanqr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_scanqr.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_scanqr.setText("")
        self.btn_scanqr.setObjectName("btn_scanqr")
        self.btn_donate = QtWidgets.QPushButton(self.counting_page)
        self.btn_donate.setGeometry(QtCore.QRect(517, 969, 161, 241))
        self.btn_donate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_donate.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_donate.setText("")
        self.btn_donate.setObjectName("btn_donate")
        self.btn_printer = QtWidgets.QPushButton(self.counting_page)
        self.btn_printer.setGeometry(QtCore.QRect(286, 969, 172, 241))
        self.btn_printer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_printer.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_printer.setText("")
        self.btn_printer.setObjectName("btn_printer")
        self.lbl_donate = QtWidgets.QLabel(self.counting_page)
        self.lbl_donate.setGeometry(QtCore.QRect(527, 1170, 180, 41))
        self.lbl_donate.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_donate.setObjectName("lbl_donate")
        self.optionstitle = QtWidgets.QLabel(self.counting_page)
        self.optionstitle.setGeometry(QtCore.QRect(20, 920, 701, 31))
        self.optionstitle.setAlignment(QtCore.Qt.AlignCenter)
        self.optionstitle.setObjectName("optionstitle")
        self.lbl_printer = QtWidgets.QLabel(self.counting_page)
        self.lbl_printer.setGeometry(QtCore.QRect(286, 1170, 172, 41))
        self.lbl_printer.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_printer.setObjectName("lbl_printer")
        self.stackedWidget.addWidget(self.counting_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.time_1.setText(_translate("MainWindow", "hh : mm  dd / mm / yyyy"))
        self.number_p.setText(_translate("MainWindow", "0"))
        self.number_c.setText(_translate("MainWindow", "0"))
        self.number_un.setText(_translate("MainWindow", "0"))
        self.text_u1.setText(_translate("MainWindow", "You have inserted"))
        self.total_number.setText(_translate("MainWindow", "22"))
        self.text_u2.setText(_translate("MainWindow", "unkown objects"))
        self.text_p.setText(_translate("MainWindow", "Plastique"))
        self.text_c.setText(_translate("MainWindow", "Canette"))
        self.text_total_numb.setText(_translate("MainWindow", "Nombre total"))
        self.lbl_scanqr.setText(_translate("MainWindow", "Scanner le Qr code"))
        self.lbl_donate.setText(_translate("MainWindow", "Offrir un don"))
        self.optionstitle.setText(_translate("MainWindow", "Veuillez choisir la méthode pour récupérer vos points "))
        self.lbl_printer.setText(_translate("MainWindow", "Imprimer le ticket"))

from .resources import *